name: Check PHP

on: [pull_request]

jobs:
  validate-psr12:
    name: Validate Against PSR12
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: composer build:dev

      - name: Lint PHP
        run: composer lint

  analyse:
    name: Analyse Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: composer build:dev

      - name: Analyse PHP
        run: composer psalm

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: composer build:dev

      - name: Test PHP
        run: composer phpunit
